### ISSUE TITLE
img2sdat not support conversion vendor.new.dat

### ISSUE THREAD

**Issue by ale8530** [xpirt/img2sdat#12]
The tool does not support conversion to vendor.new.dat, if I run the command:

python img2dat.py vendor.img folderoutput 4

I always create system.new.dat, system.transfer.list and system.patch.dat, can you fix this problem kindly?

**Comment by ingbrzy** [comment]
confirmed..
while converting vendor.img, it generate system.new.dat

@xpirt here is a ROM zip for your tests
http://bigota.d.miui.com/V9.5.4.0.OEICNFA/miui_WHYRED_V9.5.4.0.OEICNFA_b18a3c94aa_8.1.zip

Thank you for solving this issue..

**Comment by xpirt** [comment]
Fixed. 3fb0624c18081d46b83189a95365a72629409b5d

Closed.

**Comment by TipzTeam** [comment]
Still doesn't work for me.
