### ISSUE TITLE
Magic Error

### ISSUE THREAD

**Issue by rktaiwala** [xpirt/img2sdat#2]
While converting 5.1 image it gives `ValueError: Magic should be 0xED26FF3A but is 0x00000000`

**Comment by pradeep1806** [comment]
Did you find solution for this ???If so please kindly help me on the same.Got stuck on this for a week almost.

**Comment by rktaiwala** [comment]
Use older version

**Comment by pradeep1806** [comment]
Older version mean ?  Should use that parse file from android jellybean ?

Use older version

**Comment by pradeep1806** [comment]
Because I should use only android  5.1 image actually.  . .

**Comment by rktaiwala** [comment]
Search on xda forum and you will get what you want. I'm no where near my
systems otherwise I would have given you the file that worked for me.

**Comment by pradeep1806** [comment]
Thank you so much . I'll check it out ☺☺

**Comment by pradeep1806** [comment]
I could not make it yet.It will be great if you could share me working files when you get time.Thanks .

**Comment by miuirussia** [comment]
Use sparse image, not raw

**Comment by matriex** [comment]
It's not a bug , it's fault of ext4, Sparse image will work, Or try to convert ext4 to Sparse by this binary, [img2simg(win)](https://github.com/matriex/System_Extractor-WIN/blob/master/bin/img2simg.exe)
And the script img2dat.py works fine with Python2.7 but doesn't with Python3.x

**Comment by xpirt** [comment]
Not an img2sdat binary issue.

Closed.
