### ISSUE TITLE
Break level system.transfer.list for android 5.x and 6.x

### ISSUE THREAD

**Issue by ale8530** [xpirt/img2sdat#4]
The new tool generates errors for older versions.

For example, Android 5.1 had to be level 2 instead has been compiled as a level 4 as attached files.

new system.transfer.list-->http://pastebin.com/g8hRTvn6
original system.transfer.list-->http://pastebin.com/1D7Ce6G4

**Comment by xpirt** [comment]
Confirmed. 

As img2sdat binary cannot determine which system you are trying to compress, I have to add the ability to choose the correct one, as a workaround.

**Comment by ale8530** [comment]
Thanks :)
