### ISSUE TITLE
Problem with common

### ISSUE THREAD

**Issue by Aleonair** [xpirt/img2sdat#7]
Ubuntu 16.04 LTS, all software installed.
`alex_mercer@MacBookPro:~/UNPACK/AKITCHEN$`
` ./img2sdat.py system_sparse.img`
`Traceback (most recent call last):`
`  File "./img2sdat.py", line 10, in <module>`
`    import common, blockimgdiff, sparse_img`
`ImportError: No module named common`
`alex_mercer@MacBookPro:~/UNPACK/AKITCHEN$`

**Comment by xpirt** [comment]
do you have the common.py file within the same folder?

**Comment by Aleonair** [comment]
No, on XDA was not written about it. So, it must be there?

**Comment by xpirt** [comment]
the img2sdat.py needs all the files present in this repository :)

**Comment by Aleonair** [comment]
Thank you, now it is perfectly working)
Closed
